os:
  - linux
  - osx
language: node_js
node_js:
  - '12'
  - '10'
  - '8'
  - '6'
compiler:
  - clang
  - gcc
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      ./build/linux.sh;
    fi
  - if [ $TRAVIS_OS_NAME = osx ]; then
      ./build/osx.sh;
    fi
script:
  - npm test
